name: multitextor
version: "2.0.0-beta"
summary: Cross platform console mode text editor
description: |
  Multitextor is simple cross platform console mode text editor.
  It has very simple interface same in different environments (with menu and dialog).
  Editor supports mouse and keyboard cursor movement.
  It has multi-window editing, split view mode with 2 panels.
  Can clear works with different text code pages. Has different selecting modes.
  Can work with files over 4 GBytes (with small memory using).
  Has deep Undo/Redo buffer.
icon: docs/m.png
license: BSD-2-Clause

base: core18
confinement: devmode #classic
grade: stable

apps:
  multitextor:
    command: usr/bin/multitextor

parts:
  gcc-9:
    plugin: nil
    override-pull: |
      apt install -y software-properties-common
      add-apt-repository -yu ppa:ubuntu-toolchain-r/test
      apt update
      apt install -y gcc-9 g++-9
      update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 --slave /usr/bin/g++ g++ /usr/bin/g++-9
      
  cmake:
    plugin: nil
    override-pull: |
      apt remove --purge -y cmake
      snap install cmake --classic

  multitextor:
    source: https://github.com/vikonix/multitextor.git
    source-branch: main
    source-depth: 1
    plugin: cmake
    organize:
      snap/multitextor/current/usr: usr
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - g++
      - libncurses5-dev
      - libgpm-dev
    stage-packages:
      - libstdc++6
      - libtinfo5
    prime:
      - -usr/share

  config:
    source: .
    plugin: dump
    organize:
      snap/multitextor/current/usr: usr
    override-stage: |
      mkdir -p $SNAPCRAFT_STAGE/usr/share/Multitextor
      cp -a -r $SNAPCRAFT_PART_SRC/configurations/config $SNAPCRAFT_STAGE/usr/share/Multitextor/config
      cp -a -r $SNAPCRAFT_PART_SRC/configurations/parser $SNAPCRAFT_STAGE/usr/share/Multitextor/parser
    override-prime: |
      mkdir -p $SNAPCRAFT_PRIME/usr/share/Multitextor
      cp -a -r $SNAPCRAFT_STAGE/usr/share/Multitextor/config $SNAPCRAFT_PRIME/usr/share/Multitextor/config
      cp -a -r $SNAPCRAFT_STAGE/usr/share/Multitextor/parser $SNAPCRAFT_PRIME/usr/share/Multitextor/parser

layout:
  /usr/share/Multitextor:
    symlink: $SNAP/usr/share/Multitextor
